### ISSUE TITLE
Chef Search Doesn't Include Hostname Attribute for Rundeck

### ISSUE THREAD

**Issue by MattMencel** [atheiman/better-chef-rundeck#22]
I've got this working in Rundeck, but jobs won't run because the node attributes created from Chef don't include a "hostname".

Here's a node:
```
db02:
  environment: testing
  fqdn: db02.here.com
  ip: 10.50.2.82
  run_list:
  - recipe[base]
  - recipe[db]
  roles: []
  platform: centos
  tags: []
```

When I try to run jobs or commands I get:
`java.lang.IllegalArgumentException: Null hostname value
`

I've tried overriding the hostname in the node request from Chef, indicated in your README, like "http://127.0.0.1:9292/*:*?default_hostname=${node.fqdn}", but the jobs don't seem to want to use an option like that when they run.

I'm probably doing something wrong here.  If you can help point me in the right direction I would appreciate it.
